catalog:
  '@antfu/eslint-config': ^6.7.1
  '@bitcoinerlab/secp256k1': ^1.2.0
  '@ethereumjs/wallet': ^10.0.0
  '@nuxt/ui': ^4.2.1
  '@solana/kit': ^5.1.0
  '@tarocch1/eslint-config': ^4.2.2
  '@types/node': ^24.10.4
  '@vitejs/plugin-vue': ^6.0.3
  '@vitejs/plugin-vue-jsx': ^5.1.2
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^13.9.0
  bip32: ^5.0.0
  bip39: ^3.1.0
  bitcoinjs-lib: ^7.0.0
  bs58: ^6.0.0
  buffer: ^6.0.3
  eslint: ^9.39.2
  husky: ^9.1.7
  lint-staged: ^16.2.7
  micro-key-producer: ^0.8.2
  prettier-plugin-lint-md: ^1.0.1
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  vite: ^7.3.0
  vue: ^3.5.25
  vue-router: ^4.6.4
  zod: ^4.2.0

catalogMode: strict
