catalog:
  '@antfu/eslint-config': ^5.2.1
  '@bitcoinerlab/secp256k1': ^1.2.0
  '@ethereumjs/wallet': ^10.0.0
  '@nuxt/ui': ^3.3.2
  '@solana/kit': ^3.0.0
  '@tarocch1/eslint-config': ^4.0.1
  '@types/node': ^24.3.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^13.8.0
  bip32: 5.0.0-rc.0
  bip39: ^3.1.0
  bitcoinjs-lib: ^6.1.7
  bs58: ^6.0.0
  buffer: ^6.0.3
  eslint: ^9.34.0
  husky: ^9.1.7
  lint-staged: ^16.1.5
  micro-key-producer: ^0.8.2
  tailwindcss: ^4.1.12
  typescript: ^5.9.2
  vite: ^7.1.3
  vue: ^3.5.20
  vue-router: ^4.5.1
  zod: ^4.1.4

catalogMode: strict
